### ISSUE TITLE
does not open auth dialogue and does not look like its doing anything.

### ISSUE THREAD

**Issue by manish-shukla01** [OfficeDev/office-js-helpers#100]
var authenticator = new OfficeHelpers.Authenticator();
        authenticator.endpoints.registerFacebookAuth('xyz');
        authenticator
            .authenticate(OfficeHelpers.DefaultEndpoints.Facebook)
            .then(function (token) {
                var fbtoken = token;

            })

it always goes into the .then part but there is never a token or whatever appid i pass, it just goes through. not sure what i am missing. i just created a new excel addin and followed direction to include the code.

**Comment by manish-shukla01** [comment]
@casieber 
and @Zlatkovsky can you guys provide some quidance..i asked this question on stackoverflow also..
https://stackoverflow.com/questions/51800835/office-addin-auth-using-helper-js

**Comment by manish-shukla01** [comment]
i was actually able to get the auth dialogue open up by forcing it to reauthenticate..
.authenticate(OfficeHelpers.DefaultEndpoints.Microsoft, true)
but now i am getting new error:
DialogError
   at i.sent (https://unpkg.com/@microsoft/office-js-helpers@1.0.0/dist/office.helpers.min.js:1:25936)
   at Anonymous function (https://unpkg.com/@microsoft/office-js-helpers@1.0.0/dist/office.helpers.min.js:1:28303)
   at Anonymous function (https://unpkg.com/@microsoft/office-js-helpers@1.0.0/dist/office.helpers.min.js:1:26783)
   at Anonymous function (https://unpkg.com/@microsoft/office-js-helpers@1.0.0/dist/office.helpers.min.js:1:26127)
   at a (https://unpkg.com/@microsoft/office-js-helpers@1.0.0/dist/office.helpers.min.js:1:25711)
   at n (https://unpkg.com/core-js/client/core.min.js:9:484)
   at Anonymous function (https://unpkg.com/core-js/client/core.min.js:9:631)
   at t (https://unpkg.com/core-js/client/core.min.js:7:26895)
